version: '3.4'

services:
  reqdc:
    build:
      context: ..
      args:
        - DOMAIN=localhost
        - KEY=def000000d963d5c2d0bd1b9ca2fc0f50055466cfb757ff87f320fa24d7e92a33a55604051db6a80dbda0d75963f27127bccc742d4364299e80abdf6a9b609e5da802277
        - ENVNAME=local
    ports:
      - 12100:80
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootxx
      MONGO_INITDB_ROOT_PASSWORD: examplqq
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: