version: '3.4'

services:
  reqdc:
    volumes:
      - /mnt/htdocs/reqdc:/var/www/reqdc
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootxx
      ME_CONFIG_MONGODB_ADMINPASSWORD: examplqq